### ISSUE TITLE
Zero to Sixty in Sixty Minutes

### ISSUE THREAD

**Issue by seatv** [ladaapp/lada#15]
Installing lada on mint is a breeze!

It took me all of sixty minutes to swap out my NVMe drive, plop in a a new one, install Mint and install lada, wow!
![image](https://github.com/user-attachments/assets/e3fab0f5-31ac-4295-bff4-fb20ca70b316)

**Comment by seatv** [comment]
I dragged and dropped a video, 1080p, about 20 minutes long. Running CPU version. I saw a spinning wheel, left to get some dinner and came back, and the app was gone from the desktop, no messages, nothing. Nothing in the folder where the source video was nor in the Video folder.

Not sure what happened, or where to look for troubleshooting.

**Comment by leoRubberduck** [comment]
> I dragged and dropped a video, 1080p, about 20 minutes long. Running CPU version. I saw a spinning wheel, left to get some dinner and came back, and the app was gone from the desktop, no messages, nothing. Nothing in the folder where the source video was nor in the Video folder.
> 
> Not sure what happened, or where to look for troubleshooting.

Yeah happened to me. Fix for me is don't drag and drop , instead click on the open , find the video then press open .

**Comment by seatv** [comment]
The second time around, I opened the file, by navigating to where it is. Left it to run overnight, and now lada is gone from the desktop, i.e. it is not running, and not sure where to look for the output. @leoRubberduck , where do the results go. I have not changed any settings. Btw, I do not have a CUDA GPU, so I am running in CPU mode.

**Comment by ladaapp** [comment]
> the app was gone from the desktop, no messages, nothing.

The app will not close itself, maybe the OS killed it. You can start the app from a command line `flatpak run io.github.ladaapp.lada`. Maybe you'll see something in the logs there.
Next version 0.3.1 will include a fix to not block GUI thread while running in preview mode. Maybe this could be related as some OS will kill unresponsive apps automatically.

> Fix for me is don't drag and drop

That is probably a different issue. Drag and drop works only if the app you're draggin from (your file browser) also supports
[File Transfer Portal](https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.FileTransfer.html). At least when running via flatpak (sandbox).
Make sure you're using a fairly recent file browser which implements that protocol. E.g. nautilus or PCManFM (QT version). Otherwise you'll have to use the file picker dialog as you suggested as a workaround.

> so I am running in CPU mode.
Brave soul, that will take forever. If you want to try it still I would recommend using the CLI (instructions how to run CLI if installed via flathub are in the README)

**Comment by leoRubberduck** [comment]
> The second time around, I opened the file, by navigating to where it is. Left it to run overnight, and now lada is gone from the desktop, i.e. it is not running, and not sure where to look for the output. @leoRubberduck , where do the results go. I have not changed any settings. Btw, I do not have a CUDA GPU, so I am running in CPU mode.

I got Linux mint too. When I press export it takes my to the folders and ask me where I want to save it . Only once I press save , will it start the export. Mine would be something like a results.mp4 in downloads or something. Another thing if you running Linux mint , go to update manager, there is probably loads of updates your system needs. After I installed lada and had issues , I noticed lots of updates appeared for me to download. So check that too

**Comment by seatv** [comment]
I am going to make the video clip smaller, about 3 minutes, so that I can watch in real time what happens. I used the 20 minutes hoping to compare it to the results to the one from DeepMosaic.

I shall try both command line and GUI.

@ladaapp , I agree, the OS probably killed it, I should look for some system log to see if that happened. I am sure there is way. At first, my power management was set to Turn Off display in 15 minutes. I thought that might be the problem and changed it.

**Comment by ladaapp** [comment]
@seatv I've added an issue regarding power management https://github.com/ladaapp/lada/issues/17

**Comment by leoRubberduck** [comment]
Oh does that mean mine is the CPU version if I just install the app? Mines so fast I thought it was my gpu

**Comment by seatv** [comment]
> > the app was gone from the desktop, no messages, nothing.
@ladaapp , my issue was an user error. I did not click export. I opened the file and clicked export on  2 minute clip. Now it is exporting, I have a very old ThinkCentre Tiny desktop (u can get one refurb, lightly used corp discards for less than the price of a decent GPU ) chugging along. All it is doing now is this browser and lada, LOL. 

@leoRubberduck , forgot to note the start time, but I know it has been thirty minutes and about 2/3 of the way through.

**Comment by seatv** [comment]
Flatpack installation does not bring the CLI tool; I am correct?

**Comment by ladaapp** [comment]
It does. The README mentions how to run the CLI when installed via flatpak
https://github.com/ladaapp/lada?tab=readme-ov-file#cli

**Comment by ladaapp** [comment]
That sounds weird. Are you running latest version 0.3.1 of lada? CLI or GUI?
On GUI you can switch between detection and restoration mode but on CLI thought there is no option to export detection results. :thinking: ..

**Comment by seatv** [comment]
> That sounds weird. Are you running latest version 0.3.1 of lada? CLI or GUI? On GUI you can switch between detection and restoration mode but on CLI thought there is no option to export detection results. 🤔 ..

I am running the GUI version from flatpack. Installed on Monday from flatpack, few minutes before the first post above.

**Comment by seatv** [comment]
thisuser@MyTinyM710q:~$ flatpak run --filesystem=host --command=lada-cli io.github.ladaapp.lada --version
Lada:  0.3.0-dev

**Comment by seatv** [comment]
@ladaapp , ran the CLI, however, I got the following error message:
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU
I assume I have to provide a value for --device DEVICE       torch device to run the models on , if I am using CPU, what is the value? This is the only argument, after looking at --help I can think of where I can specify that I do not have a cuda capable card.

**Comment by seatv** [comment]
Ok, I got it to start running in the CLI mode. Had to issue the following command:
```
flatpak run --filesystem=host --command=lada-cli io.github.ladaapp.lada --input ./Videos/TwominuteClip.mp4 --output ./Videos/TwominuteClip-restored.mp4 --device cpu
``` 
@ladaapp , the output format is decided on the filename extension. At first, my input and output files did not have dot extension, and the program erred out. Once I added .mp4 to the filename, it worked. Request enhancement would be to add a input/output format specifier - but I am sure there are more critical things to do.

**Comment by seatv** [comment]
'Wish we could multi-thread, 3 of the four cores are doing nothing:
![image](https://github.com/user-attachments/assets/7004fc4e-c7ee-4d78-ae94-119171b45a19)

**Comment by seatv** [comment]
The CPU version CLI ran to completion in [2:28:54<00:00,  2.21s/it]. On initial inspection, restoration seems good.

**Comment by seatv** [comment]
I downloaded the flatpack version and got the following error message after running a long video. Filesize of the video is about 2.5GB. I shall post detalis of the file in a few minutes.

Running in CPU Mode on Lenovo ThinkCentre M75q Gen 2 Desktop PC, AMD Ryzen 5 PRO 4650GE, 3.3GHz, 24GB RAM, running Linux Mint, same setup and version of lada as my post above; the short video ran through fine, and mosaic was removed.

```
thisuser@thisMachine:~$ flatpak run --filesystem=host --command=lada-cli io.github.ladaapp.lada --input ./Videos/thisVideo-1080p.mp4 --output ./Videos/thisVideo-1080p.mp4-restored.mp4 --device cpu
/app/lib/python3.12/site-packages/mmengine/optim/optimizer/zero_optimizer.py:11: DeprecationWarning: `TorchScript` support for functional optimizers is deprecated and will be removed in a future PyTorch release. Consider using the `torch.compile` optimizer instead.
  from torch.distributed.optim import \
Loads checkpoint by local backend from path: /app/model_weights/lada_mosaic_restoration_model_generic_v1.1.pth
Processing frames:  67%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                     | 139628/208216 [48:34:19<23:51:34,  1.25s/it]
Traceback (most recent call last):
  File "/app/bin/lada-cli", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/app/lib/python3.12/site-packages/lada/cli/remove_mosaic.py", line 66, in cli
    video_writer.write(restored_frame, restored_frame_pts, bgr2rgb=True)
  File "/app/lib/python3.12/site-packages/lada/lib/video_utils.py", line 501, in write
    self.output_container.mux(out_packet)
  File "av/container/output.pyx", line 362, in av.container.output.OutputContainer.mux
  File "av/container/output.pyx", line 380, in av.container.output.OutputContainer.mux_one
  File "av/container/core.pyx", line 256, in av.container.core.Container.err_check
  File "av/error.pyx", line 428, in av.error.err_check
av.error.OSError: [Errno 28] No space left on device: '/tmp/thiVideo-1080p.mp4-restored.tmp.mp4'
Traceback (most recent call last):
  File "av/container/output.pyx", line 28, in av.container.output.close_output
  File "av/container/core.pyx", line 256, in av.container.core.Container.err_check
  File "av/error.pyx", line 428, in av.error.err_check
av.error.OSError: [Errno 28] No space left on device
Exception ignored in: 'av.container.output.OutputContainer.__dealloc__'
Traceback (most recent call last):
  File "av/container/output.pyx", line 28, in av.container.output.close_output
  File "av/container/core.pyx", line 256, in av.container.core.Container.err_check
  File "av/error.pyx", line 428, in av.error.err_check
av.error.OSError: [Errno 28] No space left on device

```

**Comment by ladaapp** [comment]
The app will output the video first to a temporary file in /tmp. Then it will get the video stream from the temp file and the audio stream from the original file and write both to the destination you specified.
Maybe your /tmp is not big enough then? :thinking:
Maybe there is a better directory than /tmp for this purpose or I have to do it without a temp file. For now you will have to either grow your temp filesystem or slit the file into smaller chunks. You can do this with ffmpeg segment/concat filters without re-encoding.

**Comment by ladaapp** [comment]
Oh, Just found out if you specify `TMPDIR` variable. If you run the app with that env variable set to a dir of your choice the app will use it for the temp file.
```
flatpak run --env=TMPDIR=/use/this/dir/instead --filesystem=host
```
While it's running you should find a file in that directory.
Can you test and let me know if it works, then I'll add it to the readme...

**Comment by seatv** [comment]
Ran the test, in two terminal windows,  one with the  --env=TMPDIR=/temp and one without.

Where I specified the --env=TMPDIR=/temp, a file "tmp4iqflw1_ " was created in the /temp directory.
Where I did not specify the /temp, not sure where the  equivalent file is created.

In short ,  your suggestion above seems to direct creation of the temp file in the specified location.

I am using a  small file for testing, it will take  2+ days for the file to run to finish, I shall  post back once I run a test with the large file.

It is also possible that there is a file size limitation on ~/Videos folder.  Quick google search did not show up anything, people have problems with NTFS not ux file systems.

**Comment by seatv** [comment]
@ladaapp, an enhancement request: output processsing begin and end times to the console in CLI mode. I would, if I could ever get lada to build.

**Comment by ladaapp** [comment]
> Is there restriction about running more than one instance of lada on the same machine? I had done the same with DM and it would finish both processes successfully.

No restrictions. I'd assume it got killed by the OS. Lada will need a lot of resources (RAM,CPU,GPU,VRAM). I'd not recommend running multiple instances of Lada CLI/GUI in parallel unless you have multiple GPUs and a lot of RAM/CPU.

> Assuming the first set of numbers is the number of frames and 4:15:12 is the time it took to process. Am I reading this right?

Exactly

**Comment by seatv** [comment]
Back from my break, I got DM to run in hardware mode, installed all the necessary NVIDIA drivers and tested with deviceQuery and then kicked off DM. So, I now know that I have a working CUDA environment, albiet version 11.0.4 of CUDA, with the latest NVIDIA studio graphincs drivers.

I am going to pickup lada port to Windows in a week or two.
